#!/bin/sh

#
# Convenience functions
#

alias src='exec zsh'
alias untar='tar -xzvf'
alias fehopen='feh --scale-down --auto-zoom --image-bg black'
alias xres='xrdb ~/.config/X11/.Xresources'
alias startdb='sudo systemctl start mongodb'
alias stopdb='sudo systemctl stop mongodb'
alias fnmode='echo 1 | sudo tee /sys/module/hid_apple/parameters/fnmode'

#
# Setting some defaults
#

alias ls='ls --color'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

#
# Some fzf fun stuff
#

# Opening a file in the home dir from anywhere
alias eh='nvim $(cd $HOME && echo $(realpath $(fzf)))'
# Same but in the config folder
alias ec='nvim $(cd $XDG_CONFIG_HOME && echo $(realpath $(fzf)))'
# Same but with pdf's
alias book='zathura $(cd $HOME/Desktop/books && echo $(realpath $(fzf)))'
# Same but with pictures
alias pic='feh --scale-down --auto-zoom --image-bg black $(cd $HOME/Pictures && echo $(realpath $(fzf)))'

#
# Opening some specific files
#

alias aliases='nvim $XDG_CONFIG_HOME/zsh/aliases'
alias nconf='cd $XDG_CONFIG_HOME/nvim && nvim'
alias cdst='cd $HOME/Documents/suckless/st-0.8.5'
alias cddmenu='cd $HOME/Documents/suckless/dmenu-5.1'
alias cddwm='cd $HOME/Documents/suckless/dwm-6.3'

