#!/bin/sh 

clock() {
    echo " $(date +%R)"
}

battery() {
    bat_stat=$(acpi -b | sed 's/,//g' | awk '{print $4}')
    bat_amnt=$(echo $bat_stat | sed 's/%//')

    low_bat="10"

    state=$(acpi -b | sed 's/,//g' | awk '{print $3}')
    state_icon=" "

    if [ "$state" != "Charging" ]; then
        if [ "$bat_amnt" -le "$low_bat" ]; then
            notify-send "Low battery bro" -u critical
        fi
        state_icon=""
    fi

    bat1="95"
    bat2="75"
    bat3="50"
    bat4="15"
    
    [ "$bat_amnt" -gt $bat1 ] && icon=" "
    [ "$bat_amnt" -gt $bat2 ] && [ "$bat_amnt" -le $bat1 ] && icon=" "
    [ "$bat_amnt" -gt $bat3 ] && [ "$bat_amnt" -le $bat2 ] && icon=" "
    [ "$bat_amnt" -gt $bat4 ] && [ "$bat_amnt" -le $bat3 ] && icon=" "
    [ "$bat_amnt" -le $bat4 ] && icon=" "

    echo "$icon$bat_stat$state_icon"
}

while true; do
    xsetroot -name "$(clock) | $(battery) |  "
    sleep 10s
done &
